### Проект 2. Исследование объявлений о продаже квартир
В вашем распоряжении данные сервиса Яндекс.Недвижимость — архив объявлений о продаже квартир в Санкт-Петербурге и соседних населённых пунктах за несколько лет.
Нужно научиться определять рыночную стоимость объектов недвижимости.
Ваша задача — установить параметры.
Это позволит построить автоматизированную систему: она отследит аномалии и мошенническую деятельность.

По каждой квартире на продажу доступны два вида данных.
Первые вписаны пользователем, вторые — получены автоматически на основе картографических данных.
Например, расстояние до центра, аэропорта, ближайшего парка и водоёма.

Описание данных :
total_images — число фотографий квартиры в объявлении

last_price — цена на момент снятия с публикации

total_area — площадь квартиры в квадратных метрах (м²)

first_day_exposition — дата публикации

rooms — число комнат

ceiling_height — высота потолков (м)

floors_total — всего этажей в доме

floor — этаж

is_apartment — апартаменты (булев тип)

living_area — жилая площадь в квадратных метрах(м²)

open_plan — свободная планировка (булев тип)

studio — квартира-студия (булев тип)

locality_name — название населённого пункта

kitchen_area — площадь кухни в квадратных метрах (м²)

balcony — число балконов

airports_nearest — расстояние до ближайшего аэропорта в метрах (м)

cityCenters_nearest — расстояние до центра города (м)

parks_around3000 — число парков в радиусе 3 км

parks_nearest — расстояние до ближайшего парка (м)

ponds_around3000 — число водоёмов в радиусе 3 км

ponds_nearest — расстояние до ближайшего водоёма (м)

days_exposition — сколько дней было размещено объявление (от публикации до снятия)

Пояснение: апартаменты — это нежилые помещения, не относящиеся к жилому фонду, но имеющие необходимые условия для проживания.

In [1]:
print ('Hi everyone! Its my first project.')

Hi everyone! Its my first project.

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.options.mode.chained_assignment = None
pd.options.display.max_rows
pd.options.display.max_rows = 100000
data = pd.read_csv('C:\\Users\\lizgn\\Downloads\\real_estate_data.csv')
#Рассмотрим головную часть датасета:
data.head(10)

,Unnamed: 0,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,...,kitchen_area,balcony,locality_name,airports_nearest,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition
0,0,20,13000000.0,108.00,2019-03-07T00:00:00,3,2.70,16.0,51.00,8,...,25.00,NaN,Санкт-Петербург,18863.0,16028.0,1.0,482.0,2.0,755.0,NaN
1,1,7,3350000.0,40.40,2018-12-04T00:00:00,1,NaN,11.0,18.60,1,...,11.00,2.0,посёлок Шушары,12817.0,18603.0,0.0,NaN,0.0,NaN,81.0
2,2,10,5196000.0,56.00,2015-08-20T00:00:00,2,NaN,5.0,34.30,4,...,8.30,0.0,Санкт-Петербург,21741.0,13933.0,1.0,90.0,2.0,574.0,558.0
3,3,0,64900000.0,159.00,2015-07-24T00:00:00,3,NaN,14.0,NaN,9,...,NaN,0.0,Санкт-Петербург,28098.0,6800.0,2.0,84.0,3.0,234.0,424.0
4,4,2,10000000.0,100.00,2018-06-19T00:00:00,2,3.03,14.0,32.00,13,...,41.00,NaN,Санкт-Петербург,31856.0,8098.0,2.0,112.0,1.0,48.0,121.0
5,5,10,2890000.0,30.40,2018-09-10T00:00:00,1,NaN,12.0,14.40,5,...,9.10,NaN,городской посёлок Янино-1,NaN,NaN,NaN,NaN,NaN,NaN,55.0
6,6,6,3700000.0,37.30,2017-11-02T00:00:00,1,NaN,26.0,10.60,6,...,14.40,1.0,посёлок Парголово,52996.0,19143.0,0.0,NaN,0.0,NaN,155.0
7,7,5,7915000.0,71.60,2019-04-18T00:00:00,2,NaN,24.0,NaN,22,...,18.90,2.0,Санкт-Петербург,23982.0,11634.0,0.0,NaN,0.0,NaN,NaN
8,8,20,2900000.0,33.16,2018-05-23T00:00:00,1,NaN,27.0,15.43,26,...,8.81,NaN,посёлок Мурино,NaN,NaN,NaN,NaN,NaN,NaN,189.0
9,9,18,5400000.0,61.00,2017-02-26T00:00:00,3,2.50,9.0,43.60,7,...,6.50,2.0,Санкт-Петербург,50898.0,15008.0,0.0,NaN,0.0,NaN,289.0

In [22]:
#узнаемобщую информацию о нашем датасете:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,23699.0,1.184900e+04,6.841456e+03,0.0,5924.50,11849.00,17773.5,23698.0
total_images,23699.0,9.858475e+00,5.682529e+00,0.0,6.00,9.00,14.0,50.0
last_price,23699.0,6.541549e+06,1.088701e+07,12190.0,3400000.00,4650000.00,6800000.0,763000000.0
total_area,23699.0,6.034865e+01,3.565408e+01,12.0,40.00,52.00,69.9,900.0
rooms,23699.0,2.070636e+00,1.078405e+00,0.0,1.00,2.00,3.0,19.0
ceiling_height,14504.0,2.771499e+00,1.261056e+00,1.0,2.52,2.65,2.8,100.0
floors_total,23613.0,1.067382e+01,6.597173e+00,1.0,5.00,9.00,16.0,60.0
living_area,21796.0,3.445785e+01,2.203045e+01,2.0,18.60,30.00,42.3,409.7
floor,23699.0,5.892358e+00,4.885249e+00,1.0,2.00,4.00,8.0,33.0
kitchen_area,21421.0,1.056981e+01,5.905438e+00,1.3,7.00,9.10,12.0,112.0
balcony,12180.0,1.150082e+00,1.071300e+00,0.0,0.00,1.00,2.0,5.0
airports_nearest,18157.0,2.879367e+04,1.263088e+04,0.0,18585.00,26726.00,37273.0,84869.0
cityCenters_nearest,18180.0,1.419128e+04,8.608386e+03,181.0,9238.00,13098.50,16293.0,65968.0
parks_around3000,18181.0,6.114075e-01,8.020736e-01,0.0,0.00,0.00,1.0,3.0
parks_nearest,8079.0,4.908046e+02,3.423180e+02,1.0,288.00,455.00,612.0,3190.0
ponds_around3000,18181.0,7.702547e-01,9.383456e-01,0.0,0.00,1.00,1.0,3.0
ponds_nearest,9110.0,5.179809e+02,2.777206e+02,13.0,294.00,502.00,729.0,1344.0
days_exposition,20518.0,1.808886e+02,2.197280e+02,1.0,45.00,95.00,232.0,1580.0

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23699 entries, 0 to 23698
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            23699 non-null  int64
 1   total_images          23699 non-null  int64
 2   last_price            23699 non-null  float64
 3   total_area            23699 non-null  float64
 4   first_day_exposition  23699 non-null  object
 5   rooms                 23699 non-null  int64
 6   ceiling_height        14504 non-null  float64
 7   floors_total          23613 non-null  float64
 8   living_area           21796 non-null  float64
 9   floor                 23699 non-null  int64
 10  is_apartment          2775 non-null   object
 11  studio                23699 non-null  bool
 12  open_plan             23699 non-null  bool
 13  kitchen_area          21421 non-null  float64
 14  balcony               12180 non-null  float64
 15  locality_name         23650 non-null  object
 16  airports_nearest      18157 non-null  float64
 17  cityCenters_nearest   18180 non-null  float64
 18  parks_around3000      18181 non-null  float64
 19  parks_nearest         8079 non-null   float64
 20  ponds_around3000      18181 non-null  float64
 21  ponds_nearest         9110 non-null   float64
 22  days_exposition       20518 non-null  float64
dtypes: bool(2), float64(14), int64(4), object(3)
memory usage: 3.8+ MB

# kbkh

## bb

### h